# .swiftlint.yml
excluded:
  - Carthage
  - Pods
  - DerivedData

# Let swift-format own layout
disabled_rules:
  - opening_brace
  - closing_brace
  - colon
  - comma
  - trailing_whitespace
  - vertical_whitespace_between_cases

# Keep these, but align with formatter settings
line_length:
  warning: 100
  error: 120
  ignores_urls: true
  ignores_comments: true
  ignores_interpolated_strings: true

vertical_whitespace:
  max_empty_lines: 1

# If you want import checks, keep this ON (matches OrderedImports)
opt_in_rules:
  - sorted_imports