excluded:
  - Pods
  - Little Moments.xcodeproj
  - Little MomentsTests
  - Little MomentsUITests
  - fastlane

disabled_rules:
  - trailing_whitespace
  - line_length
  - identifier_name

opt_in_rules:
  - empty_count
  - empty_string
  - fatal_error_message
  - force_unwrapping
  - implicitly_unwrapped_optional
  - private_outlet
  - prohibited_super_call
  - redundant_nil_coalescing
  - sorted_imports

analyzer_rules:
  - unused_declaration
  - unused_import

force_cast: warning
force_try: warning
force_unwrapping: warning

cyclomatic_complexity:
  warning: 15
  error: 25

type_body_length:
  warning: 300
  error: 500

file_length:
  warning: 500
  error: 1000

function_body_length:
  warning: 50
  error: 100

reporter: "xcode" 