//
//  SettingsView.swift
//  Just Now
//
//  Created by Illya Bomash on 5/29/23.
//

// Import JustNowSettings from Models folder
import LittleMoments
import SwiftUI

struct SettingsView: View {
  @Environment(\.presentationMode)
  var presentationMode

  @ObservedObject var settings: JustNowSettings = JustNowSettings.shared

  var body: some View {
    NavigationView {
      Form {
        Section(header: Text("Health")) {
          Toggle(isOn: $settings.writeToHealth, label: { Text("Write sessions to Health") })
        }

        Section(header: Text("Sounds")) {
          Toggle(isOn: $settings.ringBellAtStart, label: { Text("Ring bell at start of session") })
        }

        Section(header: Text("Display")) {
          Toggle(isOn: $settings.showSeconds, label: { Text("Show seconds") })
          Toggle(isOn: $settings.enableLiveActivities, label: { Text("Enable Live Activities") })
        }

        Section(header: Text("About")) {
          Text("Coded by Illya Bomash, 2023–2025.")
          if let url = URL(string: "https://github.com/ibomash/LittleMoments") {
            Link(destination: url) {
              Text("Code available on GitHub.")
            }
          }
          if let attributedString = try? AttributedString(
            markdown:
              "Enjoying it? Please offer _dana_ to teachers whose teachings resonate with you, or to people doing good things in your local community."
          ) {
            Text(attributedString)
          }

        }

        Section(header: Text("Credits")) {
          Text("Bell sound downloaded from user fauxpress on freesound.org.")
          Text(
            "The prompt included on the main screen was heavily influenced by the teachings of Loch Kelly."
          )
          Text(
            "The initial app icon was generated by DALL-E. I would like to commission an artist for the final icon."
          )
          Text(
            "AI was used to help with coding. I enjoy coding but I've never worked with Swift or iOS before. ChatGPT and GitHub Copilot were both used to help put this together as a hobby project."
          )
        }
      }
      .navigationBarTitle("Settings")
      .navigationBarItems(
        trailing: Button(
          "Dismiss",
          action: {
            self.presentationMode.wrappedValue.dismiss()
          }))
    }
  }
}

// JustNowSettings class has been moved to LittleMoments/Features/Settings/Models/JustNowSettings.swift

struct SettingsView_Previews: PreviewProvider {
  static var previews: some View {
    SettingsView()
  }
}
