//
//  SettingsView.swift
//  Just Now
//
//  Created by Illya Bomash on 5/29/23.
//

import Foundation
import SwiftUI

struct SettingsView: View {
  @Environment(\.presentationMode)
  var presentationMode

  @ObservedObject var settings: JustNowSettings = JustNowSettings.shared

  var body: some View {
    NavigationView {
      Form {
        Section(header: Text("Health")) {
          Toggle(isOn: $settings.writeToHealth, label: { Text("Write sessions to Health") })
        }

        Section(header: Text("Sounds")) {
          Toggle(isOn: $settings.ringBellAtStart, label: { Text("Ring bell at start of session") })
        }

        Section(header: Text("Display")) {
          Toggle(isOn: $settings.showSeconds, label: { Text("Show seconds") })
        }

        Section(header: Text("About")) {
          Text("Coded by Illya Bomash in 2023.")
          if let url = URL(string: "https://github.com/ibomash/LittleMoments") {
            Link(destination: url) {
              Text("Code available on GitHub.")
            }
          }
          if let attributedString = try? AttributedString(
            markdown:
              "Enjoying it? Please offer _dana_ to teachers whose teachings resonate with you, or to people doing good things in your local community."
          ) {
            Text(attributedString)
          }

        }

        Section(header: Text("Credits")) {
          Text("Bell sound downloaded from user fauxpress on freesound.org.")
          Text(
            "The prompt included on the main screen was heavily influenced by the teachings of Loch Kelly."
          )
          Text(
            "The initial app icon was generated by DALL-E. I would like to commission an artist for the final icon."
          )
          Text(
            "AI was used to help with coding. I enjoy coding but I've never worked with Swift or iOS before. ChatGPT and Github Copilot were both used to help put this together as a hobby project."
          )
        }
      }
      .navigationBarTitle("Settings")
      .navigationBarItems(
        trailing: Button(
          "Dismiss",
          action: {
            self.presentationMode.wrappedValue.dismiss()
          }))
    }
  }
}

class JustNowSettings: ObservableObject {
  static let shared = JustNowSettings()

  private let userDefaults = UserDefaults.standard

  var writeToHealth: Bool
  {
    get {
      return userDefaults.bool(forKey: "writeToHealth")
    }
    set {
      if newValue {
        HealthKitManager.shared.requestAuthorization { (success, error) in
          if !success {
            print("HealthKit permission denied: ", error?.localizedDescription ?? "Unknown error")
            return
          }
        }
      }
      userDefaults.set(newValue, forKey: "writeToHealth")
      userDefaults.synchronize()
    }
  }

  var ringBellAtStart: Bool {
    get {
      if let value = userDefaults.object(forKey: "ringBellAtStart") as? Bool {
        return value
      } else {
        return true  // Default value
      }
    }
    set {
      userDefaults.set(newValue, forKey: "ringBellAtStart")
      userDefaults.synchronize()
    }
  }

  var showSeconds: Bool {
    get {
      if let value = userDefaults.object(forKey: "showSeconds") as? Bool {
        return value
      } else {
        return true  // Default value
      }
    }
    set {
      userDefaults.set(newValue, forKey: "showSeconds")
      userDefaults.synchronize()
    }
  }

  private init() {}
}

struct SettingsView_Previews: PreviewProvider {
  static var previews: some View {
    SettingsView()
  }
}
